const searchTerms = {
  state: {
    keywords: [{name: "apple"}],
    searchTerm: '',
    keywordsTracker: ['apple', 'banana'],
    thumbnailSrc: '',
    thumbnailActive: false,
    hardCoded: ["amy elliot",
"bradly host",
"carla ryan",
"corey petty",
"david stobbe",
"jackie chiu",
"jamie wilde",
"joe ryan",
"kyle elliot",
"laura whitesides host",
"lesley whitesides",
"meredith host",
"patrick mcinerney",
"taylor host",
"tom halverson",
"valerie fay",
"aguas calientes",
"angkor wat",
"annie moore statue",
"aquas calientes",
"austria",
"baan dam",
"bagaces",
"barranco",
"barrio de la presa",
"batu caves",
"belgravia",
"bogota old town",
"bogota",
"bogotá",
"botero museum",
"british columbia",
"british virgin islands",
"california",
"cambodia",
"canada",
"caribbean",
"central",
"centro histórico",
"centro",
"chai wan",
"chang wat chiang mai",
"chang wat chiang rai",
"chek lap kok",
"chiang mai",
"chiang rai",
"chinchero",
"chūō-ku",
"clear water bay",
"cliffs of moher",
"cn tower",
"coal harbour",
"cobh",
"coco",
"colombia",
"comunidad de madrid",
"cork",
"costa rica",
"county clare",
"county cork",
"county dublin",
"county galway",
"cusco",
"cuzco",
"cửa nam",
"da nang",
"downtown",
"dragon bridge",
"dubai",
"dublin",
"east end",
"england",
"europe",
"florida",
"fujikawaguchiko-machi",
"fulham",
"galway cathedral",
"galway",
"germania",
"gia ngu restaurant",
"grand haven",
"guanacaste province",
"guanajuato",
"ha long bay",
"hanoi",
"hard rock hotel",
"harrods",
"hawaii",
"hiroshima",
"ho long bay",
"hofburg",
"hoi an old town",
"hoi an",
"hollywood",
"hong kong island",
"hong kong",
"honolulu",
"hà nội",
"hà n���i",
"hàng bài",
"hàng bạc",
"hàng trống",
"hòa cường nam",
"hồng gai",
"icc",
"innere stadt",
"intercontinental da nang",
"ireland",
"japan",
"jardines del buen retiro",
"jost van dyke",
"kalamazoo",
"kanagawa-ken",
"kaohsiung city",
"kaohsiung",
"kawaguchiko",
"kilgarvan",
"kissimmee",
"knightsbridge",
"kuala lumpur",
"la candelaria",
"la catedral",
"la fortuna",
"la paz",
"la petaca",
"laguna de masaya",
"lantau island",
"las angeles",
"las nieves",
"las vegas",
"lima",
"lislorkan north",
"london",
"los angeles",
"machu picchu sanctuary lodge",
"machu picchu",
"madame tussauds hollywood",
"madrid",
"malaysia",
"maras salt mines",
"mexico",
"michigan",
"minh an",
"miraflores",
"miyajima",
"monserrate hill",
"moray",
"mrt formosa boulevard station",
"mt fuji",
"mt. fuji",
"mui wo",
"municipalidad metropolitana de lima",
"my khe beach",
"mỹ an",
"nagoya",
"naniwa-ku",
"nara",
"nara-ken",
"nara-shi",
"natural history museum vienna",
"natural history museum",
"nevada",
"new territories",
"nhật tân",
"niagara falls",
"nicaragua falls",
"nicaragua",
"north dock",
"north point",
"nuevo méxico",
"ocean park",
"ollantaytambo",
"ontario",
"osaka",
"panama city",
"panama",
"panamá",
"parque central de miraflores",
"parroquia virgen milagrosa",
"peru",
"phước mỹ",
"phước ninh",
"plaza de armas del cusco",
"plaza de bolivar",
"plaza mayor",
"provincia de alajuela",
"provincia de guanacaste",
"qosqo",
"quảng nam",
"quảng ninh",
"river corrib",
"rosewood hotel san miguel",
"royal palace madrid",
"sacred valley",
"sai wan ho",
"saint thomas",
"san antonio",
"san carlos",
"san francisco",
"san miguel de allende",
"san miguel",
"sangkat nokor thum",
"sangkat svay dangkum",
"santa fé",
"shau kei wan",
"shinjuku",
"shinsaibashi",
"shisaibashi",
"siem reap province",
"siem reap pub street",
"siem reap",
"skylodge",
"spain",
"st joseph cathedral hanoi",
"st. thomas",
"stamford bridge stadium",
"stephansdom cathedral",
"switzerland ",
"switzerland",
"sword lake",
"tainan city",
"tainan",
"taiwan",
"tambon chang khlan",
"tambon nang lae",
"tambon pa o don chai",
"tambon phra sing",
"tambon si phum",
"tambon su thep",
"teatro la plaza",
"teeraghbeg",
"temple bar street",
"temple bar",
"thailand",
"the cathedral church of st colman",
"the university of dublin",
"thọ quang",
"titanic museum cobh",
"tokoname",
"tokyo",
"tsim sha tsui",
"tst",
"tuần châu",
"tōkyō-to",
"u.s. virgin islands",
"uae",
"uk",
"united arab emirates",
"united kingdom",
"united states virgin islands",
"united states",
"urubamba",
"usa",
"vancouver",
"vienna",
"vietnam",
"virgin gorda",
"wat phra singh",
"wat rong khun",
"wien",
"xinxing district",
"yamanashi-ken",
"yau yue wan",
"yokohama",
"zona centro",
"zurich national museum",
"zurich old town",
"zurich",
"đà nẵng",
"ōsaka-fu",
"เทศบาลนครเชียงใหม่",
"平安里",
"平通里",
"明莊里",
"民權里",
"海頭里",
"港仔里",
"華平里",
"sky",
"tree",
"tourism",
"building",
"city",
"cloud",
"tourist attraction",
"mountain",
"water",
"recreation",
"vacation",
"landmark",
"facade",
"plant",
"hill station",
"highland",
"urban area",
"grass",
"house",
"mount scenery",
"town",
"street",
"art",
"fun",
"window",
"historic site",
"road",
"sea",
"architecture",
"ancient history",
"mountainous landforms",
"vehicle",
"rock",
"travel",
"temple",
"metropolitan area",
"hill",
"place of worship",
"river",
"reflection",
"geology",
"food",
"mountain range",
"leisure",
"car",
"waterway",
"landscape",
"girl",
"statue",
"skyline",
"national park",
"daytime",
"structure",
"sculpture",
"dish",
"hat",
"cuisine",
"waterfront",
"boat",
"town square",
"skyscraper",
"rural area",
"medieval architecture",
"body of water",
"wall",
"vegetation",
"church",
"baseball cap",
"archaeological site",
"machu picchu",
"detroit tigers",
"arch",
"religion",
"public space",
"history",
"cathedral",
"palace",
"outcrop",
"ocean",
"night",
"neighbourhood",
"nature",
"basilica",
"tower",
"plaza",
"metropolis",
"coast",
"tower block",
"shore",
"ruins",
"restaurant",
"monument",
"grassland",
"evening",
"wilderness",
"sunset",
"mountains",
"meal",
"geological phenomenon",
"field",
"shrubland",
"roof",
"outdoor structure",
"fauna",
"drink",
"cityscape",
"bank",
"sunglasses",
"smile",
"pasture",
"middle ages",
"horizon",
"cat",
"asian food",
"terrace",
"product",
"photography",
"palm trees",
"nature reserve",
"infrastructure",
"beer",
"water resources",
"village",
"royal palace of madrid",
"romantic",
"pedestrian",
"escarpment",
"château",
"chinese architecture",
"phenomenon",
"mountain village",
"lunch",
"loch",
"lighting",
"lawn",
"lake",
"headgear",
"glasses",
"garden",
"classical architecture",
"beach",
"aerial photography",
"watercourse",
"valley",
"snout",
"shrine",
"ridge",
"promontory",
"painting",
"pagoda",
"morning",
"grasses",
"flooring",
"condominium",
"coastal and oceanic landforms",
"cliff",
"breakfast",
"wood",
"wat",
"unesco world heritage site",
"transport",
"terrain",
"small to medium sized cats",
"residential area",
"plateau",
"museum",
"mural",
"glass",
"floor",
"fjord",
"dusk",
"caves",
"atmosphere",
"arecales",
"yellow",
"vision care",
"sunrise",
"street food",
"road surface",
"reservoir",
"property",
"pier",
"park",
"national trust for places of historic interest or natural beauty",
"mountain pass",
"livestock",
"light",
"leaf",
"lane",
"lake district",
"indian temple",
"grass family",
"estate",
"dog",
"day",
"dawn",
"carving",
"boating",
"bird's-eye view",
"atmosphere of earth",
"alcoholic beverage",
"alcohol",
"agriculture",
"wildlife",
"walkway",
"symmetry",
"soup",
"real estate",
"pond",
"palm tree",
"memorial",
"llama",
"island",
"iron",
"graffiti",
"friends",
"farm",
"column",
"chapel",
"canal",
"bicycle",
"art gallery",
"advertising",
"whiskers",
"water transportation",
"water feature",
"suburb",
"street art",
"steeple",
"standing",
"staircase",
"resort",
"red",
"recipe",
"plantation",
"museo botero",
"modern art",
"mammal",
"land vehicle",
"home",
"headland",
"flower",
"flora",
"figurine",
"downtown",
"dog like mammal",
"cat like mammal",
"biome",
"artwork",
"apartment",
"world heritage site",
"woody plant",
"wat rong khun",
"table",
"sunlight",
"stock photography",
"sport venue",
"snapshot",
"rainforest",
"public",
"portrait",
"picture frame",
"noodle soup",
"mode of transport",
"kitten",
"jungle",
"japanese architecture",
"historical",
"hindu temple",
"head",
"green",
"fur",
"fashion accessory",
"eyewear",
"event",
"ecoregion",
"design",
"darkness",
"crop",
"camel like mammal",
"bridge",
"bottle",
"bird",
"bedrock",
"area",
"afterglow",
"yacht",
"vertebrate",
"vegetarian food",
"united states of america",
"theme park",
"swimming pool",
"stone wall",
"stadium",
"spire",
"space",
"side dish",
"sailing",
"road bicycle",
"relax",
"ranch",
"primatial cathedral of bogotá",
"plant community",
"pint us",
"party",
"mixed-use",
"mist",
"maya civilization",
"maya city",
"mansion",
"jeans",
"interior design",
"headband",
"gate",
"furniture",
"forest",
"fashion",
"daylighting",
"cusco",
"crowd",
"costume",
"cape",
"bún bò huế",
"byzantine architecture",
"bridge–tunnel",
"blue",
"beef",
"beak",
"bay",
"bar",
"asphalt",
"asian cuisine",
"alps",
"zoo",
"winter",
"wave",
"wallpaper",
"vegetarian cuisine",
"toy",
"street light",
"stone",
"steppe",
"slum",
"signage",
"sign",
"sidewalk",
"selfie",
"sailboat",
"religious institute",
"red sky at morning",
"pint",
"paint",
"pack animal",
"neon",
"money cat",
"mixed use",
"malaysian cuisine",
"majorelle garden",
"majorelle blue",
"liqueur",
"landscaping",
"laksa",
"labyrinth",
"kiss",
"hybrid bicycle",
"hinduism",
"gold",
"glass bottle",
"fortification",
"formation",
"forehead",
"fernando botero",
"dome",
"distilled beverage",
"cycling",
"collection",
"clouds",
"child",
"cave",
"cat statue",
"brunch",
"bolívar square",
"beer bottle",
"balcony",
"art exhibition",
"arena",
"archaeology",
"alpaca",
"almudena cathedral",
"wheel",
"watercraft",
"water bird",
"volcano",
"visual arts",
"tropics",
"trees",
"thai cuisine",
"textile",
"tent",
"tarmac",
"tail",
"table salt",
"tabby cat",
"synagogue",
"stone carving",
"stately home",
"stallion",
"spring",
"sports",
"spicy",
"spanish language",
"socialite",
"soccer-specific stadium",
"sitting",
"shrub",
"shoulder",
"sedan",
"salt pan",
"sail",
"rosewood san miguel",
"rice",
"resource",
"price is right",
"port",
"pho",
"peek",
"path",
"paddy field",
"outerwear",
"old-growth forest",
"noodles",
"noodle",
"mountain bike",
"meteorological phenomenon",
"menu",
"marketplace",
"market",
"lincoln memorial reflecting pool",
"kuala lumpur",
"interaction",
"indian cuisine",
"horse",
"horse like mammal",
"highway",
"harbor",
"green dot stables",
"game show",
"gallery",
"friendship",
"fog",
"flowers",
"floodplain",
"fixed link",
"festival",
"ferry",
"fence",
"fell",
"exhibition",
"entertainment",
"ecosystem",
"eating",
"dragon",
"door",
"domestic short-haired cat",
"domestic short haired cat",
"dog breed",
"dog breed group",
"dinner",
"curry",
"cruise",
"cove",
"cool",
"contestant",
"concert",
"compact car",
"commemorative plaque",
"classical sculpture",
"chinese food",
"castle",
"carnivoran",
"breed group (dog)",
"breakwater",
"botanical garden",
"bike",
"bayou",
"batu caves",
"batchoy",
"baptistery",
"bank of the republic",
"arcade",
"animal source foods",
"ale",
"adventure",
"yard",
"yakiniku",
"worship",
"workshop",
"woodland",
"wood stain",
"wonders of the world",
"woman",
"welcome to fabulous las vegas sign",
"waterfall",
"waikiki",
"wadi",
"vendor",
"umbrella",
"trunk",
"tropical",
"trail",
"toddler",
"theatre",
"theater",
"the arts",
"thai food",
"technology",
"team",
"team sport",
"takoyaki",
"tableware",
"t-shirt",
"t shirt",
"swan",
"supper",
"street dog",
"stew",
"steamed rice",
"stained glass",
"stage",
"sports equipment",
"sporting group",
"spoon",
"soil",
"soccer specific stadium",
"sill",
"show",
"shopping",
"shoe",
"shirt",
"ship",
"service",
"seat of local government",
"san miguel de allende",
"saimin",
"saigon beer",
"royce mansion",
"royal palace of milan",
"rooster",
"roast beef",
"retail",
"resort town",
"reflecting pool",
"red meat",
"ramen",
"racing bicycle",
"race",
"race track",
"quarry",
"product design",
"pray",
"pork",
"pool",
"plaza de la villa",
"plate lunch",
"plain",
"photograph",
"pet",
"people",
"passenger",
"outdoor recreation",
"oil painting reproduction",
"ninna-ji",
"new7wonders of the world",
"naver blog",
"music",
"muscle",
"motor vehicle",
"mother",
"microsoft azure",
"meat",
"meadow",
"matsusaka beef",
"material",
"mast",
"massage",
"masque",
"mask",
"marina",
"mare",
"manufactory",
"machupicchu district",
"luxury vehicle",
"lomi",
"lima travel",
"light fixture",
"land lot",
"lager",
"kōfuku-ji",
"kobe beef",
"kimono",
"kaohsiung",
"junk food",
"jesus",
"inlet",
"inca empire",
"image",
"igneous rock",
"hotel",
"hiking",
"herd",
"headstone",
"haze",
"hardwood",
"hair",
"ha long bay",
"group",
"grazing",
"grave",
"goose",
"goats",
"goat",
"gambling",
"galliformes",
"fried food",
"fort zeelandia",
"fort provintia",
"formosa boulevard station",
"football",
"font",
"flowering plant",
"flight",
"flesh",
"flag",
"finger",
"ferris wheel",
"fault",
"family car",
"facial expression",
"face",
"european shorthair",
"english country house",
"electricity",
"earth",
"dōtonbori",
"duck",
"drunk",
"drinkware",
"drawer",
"dragon bridge",
"detroit",
"cycle sport",
"curry mee",
"cumulus",
"culture",
"cross",
"cottage",
"cooking",
"cooked rice",
"computer",
"commercial building",
"comfort food",
"clothing",
"clockenflap",
"cliffs of moher",
"city car",
"chopsticks",
"chinese noodles",
"chinese cuisine",
"chicken",
"chiang rai",
"cheek",
"ceramic",
"ceiling",
"cartagena",
"candles",
"cabin",
"bush",
"bronze",
"bronze sculpture",
"boulder",
"bogotá",
"blog",
"bird's eye view",
"bicycle accessory",
"beer glassware",
"beer glass",
"beauty",
"batholith",
"baseball park",
"bannister",
"banana",
"bamboo",
"badlands",
"backyard",
"aviation",
"automotive exterior",
"automotive design",
"artificial turf",
"art decoration",
"art collection of the bank of the republic",
"arm",
"appetizer",
"antique",
"angle",
"angkor wat",
"american wirehair",
"alley",
"alcoholic drink",
"air travel",
"aegean cat",
"abdomen",
"đồ sơn",
"zipaquirá",
"yokohama landmark tower",
"yakisoba",
"xiaolongbao",
"wufeng road",
"wood carving",
"women's college",
"wing",
"wine",
"wildflower",
"whole food",
"white",
"white shepherd",
"white rice",
"white house",
"wetland",
"waterfowl",
"water bottle",
"wat chedi luang",
"virgin island",
"villa",
"vietnam people's navy",
"vietnam fine arts museum",
"vicuña",
"vegetable",
"vault",
"university of cauca",
"uniform",
"unagi",
"unadon",
"tō-ji",
"tundra",
"tuk tuk",
"trousers",
"trophy",
"triumphal arch",
"tray",
"transmission tower",
"trail riding",
"tours",
"tournament",
"tools",
"tonkatsu",
"tom kha kai",
"toledo",
"tokyo disneysea",
"tokoname station",
"time-lapse photography",
"tights",
"tiger beer",
"tide",
"tibetan cuisine",
"tianhou temple",
"thumbs up",
"thukpa",
"thigh",
"thermae",
"the bawdies",
"text",
"tenshu",
"tempura",
"templo de san francisco",
"temple bar",
"teatro juarez",
"tea",
"taxi",
"taste",
"tapestry",
"takahatafudō station",
"taiwan under japanese rule",
"taipei",
"tabletop games",
"tabernacle chapel",
"switzerland",
"switches",
"sweetness",
"swamp",
"suspension bridge",
"sun",
"summer",
"subway",
"subcompact car",
"stupa",
"street sign",
"street name sign",
"street 08",
"steaming",
"stateroom",
"staple food",
"stamford bridge",
"stalagmite",
"stalactites",
"stalactite",
"stairs",
"stainless steel",
"spratly islands",
"sportswear",
"sport",
"speleothem",
"spandex",
"spa",
"southeast asian food",
"southeast asia",
"son",
"soldiers",
"soldier",
"soft drink",
"soda",
"sleeve",
"sleep",
"skull",
"skull statue",
"skin",
"sistine chapel",
"sinembah tanjung muda hulu",
"sindbad's storybook voyage",
"sinbad",
"silhouette",
"sicilian pizza",
"sicilian cuisine",
"short ribs",
"shopping mall",
"shop cat",
"shinto shrine",
"shelf",
"sheep",
"shadow",
"shade",
"shack",
"shachihoko",
"serveware",
"senior citizen",
"segovia",
"seabird",
"sea of galilee",
"saucer",
"sandwich",
"sand",
"sanctuary",
"sanctuary of atotonilco",
"san francisco cable car system",
"san andrés",
"salt evaporation pond",
"salt cathedral of zipaquirá",
"saint john",
"saimin food",
"saigon river",
"rubble",
"royal sunset drive",
"rowing",
"room",
"rooftop restaurant",
"rooftop bar",
"roasting",
"road trip",
"rms lusitania",
"river terraces",
"riparian zone",
"rinkū tokoname station",
"rice noodles",
"rice and curry",
"rib eye steak",
"restaraunt",
"regensburger hof",
"red curry",
"real madrid c.f.",
"raincoatromantic",
"rain",
"railroad car",
"railing",
"rail transport",
"rabits and hares",
"rabbit",
"pungsan dog",
"public utility",
"public transport",
"professional",
"produce",
"primate",
"prairie",
"potato famine",
"poster",
"porcelain",
"poolside",
"poolside restaurant",
"polder",
"plaza mayor",
"plaza de oriente",
"player",
"pizza",
"pizza stone",
"pisa",
"pint glass",
"pink",
"pillows",
"pilgrimage",
"pilgrim",
"personal protective equipment",
"personal flotation device",
"person",
"pepperoni",
"penthouse apartment",
"paw",
"parroquia de san miguel arcángel.",
"panorama",
"panda",
"pancit",
"pam trees",
"palm",
"painter",
"oysters",
"oyster vermicelli",
"overhead power line",
"organism",
"on the air",
"oil painting",
"official residence",
"octopus",
"nose",
"new year's eve",
"naver",
"natural history",
"natural history museum",
"natural foods",
"national historic landmark",
"national center for traditional arts",
"nap",
"namba",
"nam kee",
"nagoya castle",
"nagoya castle honmaru palace",
"mustang",
"musical instrument",
"musical instrument accessory",
"museo nacional del prado",
"multi-sport event",
"mud bath",
"mouth",
"mountain goat",
"motorcycle",
"motorbike",
"mother goddess",
"mosque",
"moray",
"monster",
"monkey",
"molding",
"misua",
"minivan",
"ministry of environment",
"milanoguida | visite guidate e mostre a milano",
"michael",
"mi rebus",
"metropolitano el recreo park",
"metal",
"mergini",
"menchi-katsu",
"menchi katsu",
"mekong delta",
"medellín",
"mascot",
"manor house",
"mane",
"man",
"man with a guitar",
"male",
"maldegem",
"maize",
"main station of cable car station & funicular",
"madrid–toledo high-speed rail line",
"madrid",
"madrid center- fuencarral pedestrian",
"macbook",
"macbook pro",
"luxury yacht",
"lusitania memorial",
"local food",
"lo's",
"lizejian bridge",
"liverpool f.c.",
"listed building",
"lip",
"line",
"lima region",
"lights",
"life jacket",
"leggings",
"leaf vegetable",
"le petit futé",
"las vegas",
"las vegas strip",
"laotian cuisine",
"lanterns",
"langkawi",
"landscape lighting",
"landform",
"lamian",
"lamb and mutton",
"lagoon",
"laborer",
"kunsthistorisches museum",
"korokke",
"ko lipe",
"klippe",
"khao soi",
"karst landforms",
"karaage",
"kalguksu",
"kal-guksu",
"josai",
"joint",
"jersey",
"jay",
"japanese curry",
"japanese cuisine",
"japanese castle",
"japan",
"japan women's university",
"jacuzzi",
"jacaranda",
"italy",
"italian food",
"islet",
"island hopping",
"island hoppin' brewery",
"internal angle",
"institution",
"ingredient",
"india pale ale",
"incredible art department",
"inca kola",
"illustration",
"ice",
"hut",
"human",
"human behavior",
"hub",
"hotel imperial",
"hotel exe bacata 95",
"hot tub",
"hot springs",
"hot spring",
"hot dog",
"hors d'oeuvre",
"honolulu",
"homeaway",
"hollywood",
"hokkien mee",
"hofburg",
"ho chi minh",
"hip",
"hi-standard",
"heart",
"heart for change colombia volunteer program",
"headquarters",
"hand",
"hae mee",
"hacienda",
"gumbo",
"gulai",
"guitar",
"guilty",
"guerrilla warfare",
"guard dog",
"guanajuato",
"guanaco",
"groundcover",
"grocery store",
"greengrocer",
"great famine",
"gravy",
"granite",
"grandparent",
"gothic architecture",
"goofy",
"goo",
"glen roy",
"glass mask",
"glacial landform",
"geography",
"game",
"fur clothing",
"full breakfast",
"fruit",
"fried",
"fried wontons",
"fountain",
"footwear",
"football field",
"fluvial terrace",
"fluvial landforms of streams",
"floristry",
"flavor",
"flat iron steak",
"flap",
"fk austria wien",
"fishing",
"fishing vessel",
"finger food",
"fine art",
"fc barcelona",
"fast food",
"fast food restaurant",
"fan",
"famine",
"family",
"facial hair",
"eyelash",
"eyebrow",
"eye",
"evaporation",
"european food",
"ethiopian cuisine",
"espresso",
"eritrean cuisine",
"eritrea",
"eriska",
"equestrianism",
"en blanco & negro",
"emotion",
"elevation",
"electrical",
"electrical supply",
"eggs benedict",
"egg as food",
"eel rice",
"earthquake",
"durham",
"ducks geese and swans",
"duck boat",
"dublin",
"dragon li",
"don't speak",
"doll",
"dock",
"display device",
"display case",
"dim sum",
"dim sim",
"dessert",
"deity",
"deep frying",
"deck",
"deciduous",
"death",
"daigo-ji",
"củ chi",
"cyclo-cross",
"cyclo-cross bicycle",
"cutlery",
"cup",
"cuisine of the united states",
"cuglieri",
"crypt",
"cry",
"cow goat family",
"courtyard",
"courthouse",
"couple",
"costa rica",
"corned beef",
"corncob",
"corn",
"corn on the cob",
"cookware and bakeware",
"cook",
"congress of deputies",
"concrete",
"compact mpv",
"community",
"communication",
"communal school colombe de la paix",
"common carp",
"comfort",
"colombian art",
"cola",
"coffee",
"coffee cup",
"cocktail",
"cn tower",
"clam",
"clam chowder",
"cider",
"church tabernacle",
"christmas tree",
"christmas lights",
"chowder",
"chow mein",
"chin",
"children",
"chiang mai",
"chest of drawers",
"chelsea f.c.",
"chaparral",
"chamois",
"chair",
"cemetery",
"cattle",
"catamaran",
"casper wells",
"cascading style sheets",
"cartoon",
"caribbean sea",
"capitolio nacional",
"cap",
"cao lau",
"canyon",
"canopy",
"canon powershot sx400 is",
"canh chua",
"candles workshop",
"candle workshop",
"campus",
"camping",
"camera",
"calm",
"caldas park",
"caffè americano",
"cafe",
"cactus",
"cable car",
"cabinetry",
"bust",
"burger",
"buildings",
"british shorthair",
"bridle",
"branch",
"bracelet",
"boy",
"box",
"bowl",
"botero esculturas",
"bookcase",
"bogota",
"boardwalk",
"board games",
"black sand",
"black and white",
"birds",
"big rock",
"bicycle wheel",
"bicycle saddle",
"berger blanc suisse",
"bell",
"bell tower",
"behavior",
"beer cocktail",
"bedroom",
"bed",
"bed frame",
"bazaar",
"bathtub",
"bathing",
"bath",
"baseball",
"banner",
"banana family",
"baking stone",
"bakery",
"backpacking",
"baan dam black house museum",
"b.o.g hotel",
"autumn",
"author",
"asphalt concrete",
"asian soups",
"artist",
"artful posters",
"art museum",
"army",
"arch bridge",
"arcangel church san miguel",
"arabian coast",
"anping old street",
"annual plant",
"ancient roman architecture",
"ancient lives",
"amusement ride",
"amusement park",
"american shorthair",
"american food",
"altar",
"album",
"airport terminal",
"airplane",
"airliner",
"airline",
"1983 popayán earthquake"]
  },
  getters: {
    getKeywords: state => state.keywords,
    getKeywordsTracker: state => state.hardCoded,
    getThumbnailSrc: state => state.thumbnailSrc,
    getThumbnailActive: state => state.thumbnailActive,
  },
  mutations: {
    sortKeywords:(state, payload) => {
      //sort keywords into an array to display on autocomplete
      const keywords = [];
      // const keywordsTracker = [];
      // const keywordArrays = payload.map((item, index) => {
      //   item._source.keywords.forEach((keyword)=> {
      //     if(!keywordsTracker.includes(keyword)) {
      //       keywords.push({name:keyword})
      //       keywordsTracker.push(keyword);
      //     }
      //   })
      // });

      state.hardCoded.forEach((item) => {
        keywords.push({name:item})
      })

      state.keywords = keywords;
      state.keywordsTracker = keywordsTracker;
    },
    setThumbnailSrc:(state, payload) => {
      state.thumbnailSrc = payload
      state.thumbnailActive = true;
    },
    setThumbnailUnActive:(state) => {
      state.thumbnailActive = false;
    }
  },
  actions: {
    retrieveKeywords:(context) => {
      // on load get search terms to auto complete with.
      context.commit('sortKeywords', context.rootState.elasticSearch.responseData);
    },
    retrieveThumbnail:(context, payload) => {
      context.commit('setThumbnailSrc', payload)
    },
    turnOffThumbnail: (context) => {
      context.commit('setThumbnailUnActive')
    }
  }
}

export default searchTerms
