const searchTerms = {
  state: {
    keywords: [{name: "apple"}],
    searchTerm: '',
    keywordsTracker: ['apple', 'banana'],
    thumbnailSrc: '',
    thumbnailActive: false,
    hardCoded: [
      "aguas calientes",
      "angkor wat",
      "annie moore statue",
      "aquas calientes",
      "austria",
      "baan dam",
      "bagaces",
      "barranco",
      "barrio de la presa",
      "batu caves",
      "belgravia",
      "bogota old town",
      "bogota",
      "bogotá",
      "botero museum",
      "british columbia",
      "british virgin islands",
      "california",
      "cambodia",
      "canada",
      "caribbean",
      "central",
      "centro histórico",
      "centro",
      "chai wan",
      "chang wat chiang mai",
      "chang wat chiang rai",
      "chek lap kok",
      "chiang mai",
      "chiang rai",
      "chinchero",
      "chūō-ku",
      "clear water bay",
      "cliffs of moher",
      "cn tower",
      "coal harbour",
      "cobh",
      "coco",
      "colombia",
      "comunidad de madrid",
      "cork",
      "costa rica",
      "county clare",
      "county cork",
      "county dublin",
      "county galway",
      "cusco",
      "cuzco",
      "cửa nam",
      "da nang",
      "downtown",
      "dragon bridge",
      "dubai",
      "dublin",
      "east end",
      "england",
      "europe",
      "florida",
      "fujikawaguchiko-machi",
      "fulham",
      "galway cathedral",
      "galway",
      "germania",
      "gia ngu restaurant",
      "grand haven",
      "guanacaste province",
      "guanajuato",
      "ha long bay",
      "hanoi",
      "hard rock hotel",
      "harrods",
      "hawaii",
      "hiroshima",
      "ho long bay",
      "hofburg",
      "hoi an old town",
      "hoi an",
      "hollywood",
      "hong kong island",
      "hong kong",
      "honolulu",
      "hà nội",
      "hà n���i",
      "hàng bài",
      "hàng bạc",
      "hàng trống",
      "hòa cường nam",
      "hồng gai",
      "icc",
      "innere stadt",
      "intercontinental da nang",
      "ireland",
      "japan",
      "jardines del buen retiro",
      "jost van dyke",
      "kalamazoo",
      "kanagawa-ken",
      "kaohsiung city",
      "kaohsiung",
      "kawaguchiko",
      "kilgarvan",
      "kissimmee",
      "knightsbridge",
      "kuala lumpur",
      "la candelaria",
      "la catedral",
      "la fortuna",
      "la paz",
      "la petaca",
      "laguna de masaya",
      "lantau island",
      "las angeles",
      "las nieves",
      "las vegas",
      "lima",
      "lislorkan north",
      "london",
      "los angeles",
      "machu picchu sanctuary lodge",
      "machu picchu",
      "madame tussauds hollywood",
      "madrid",
      "malaysia",
      "maras salt mines",
      "mexico",
      "michigan",
      "minh an",
      "miraflores",
      "miyajima",
      "monserrate hill",
      "moray",
      "mrt formosa boulevard station",
      "mt fuji",
      "mt. fuji",
      "mui wo",
      "municipalidad metropolitana de lima",
      "my khe beach",
      "mỹ an",
      "nagoya",
      "naniwa-ku",
      "nara",
      "nara-ken",
      "nara-shi",
      "natural history museum vienna",
      "natural history museum",
      "nevada",
      "new territories",
      "nhật tân",
      "niagara falls",
      "nicaragua falls",
      "nicaragua",
      "north dock",
      "north point",
      "nuevo méxico",
      "ocean park",
      "ollantaytambo",
      "ontario",
      "osaka",
      "panama city",
      "panama",
      "panamá",
      "parque central de miraflores",
      "parroquia virgen milagrosa",
      "peru",
      "phước mỹ",
      "phước ninh",
      "plaza de armas del cusco",
      "plaza de bolivar",
      "plaza mayor",
      "provincia de alajuela",
      "provincia de guanacaste",
      "qosqo",
      "quảng nam",
      "quảng ninh",
      "river corrib",
      "rosewood hotel san miguel",
      "royal palace madrid",
      "sacred valley",
      "sai wan ho",
      "saint thomas",
      "san antonio",
      "san carlos",
      "san francisco",
      "san miguel de allende",
      "san miguel",
      "sangkat nokor thum",
      "sangkat svay dangkum",
      "santa fé",
      "shau kei wan",
      "shinjuku",
      "shinsaibashi",
      "shisaibashi",
      "siem reap province",
      "siem reap pub street",
      "siem reap",
      "skylodge",
      "spain",
      "st joseph cathedral hanoi",
      "st. thomas",
      "stamford bridge stadium",
      "stephansdom cathedral",
      "switzerland ",
      "switzerland",
      "sword lake",
      "tainan city",
      "tainan",
      "taiwan",
      "tambon chang khlan",
      "tambon nang lae",
      "tambon pa o don chai",
      "tambon phra sing",
      "tambon si phum",
      "tambon su thep",
      "teatro la plaza",
      "teeraghbeg",
      "temple bar street",
      "temple bar",
      "thailand",
      "the cathedral church of st colman",
      "the university of dublin",
      "thọ quang",
      "titanic museum cobh",
      "tokoname",
      "tokyo",
      "tsim sha tsui",
      "tst",
      "tuần châu",
      "tōkyō-to",
      "u.s. virgin islands",
      "uae",
      "uk",
      "united arab emirates",
      "united kingdom",
      "united states virgin islands",
      "united states",
      "urubamba",
      "usa",
      "vancouver",
      "vienna",
      "vietnam",
      "virgin gorda",
      "wat phra singh",
      "wat rong khun",
      "wien",
      "xinxing district",
      "yamanashi-ken",
      "yau yue wan",
      "yokohama",
      "zona centro",
      "zurich national museum",
      "zurich old town",
      "zurich",
      "đà nẵng",
      "ōsaka-fu",
      "เทศบาลนครเชียงใหม่",
      "平安里",
      "平通里",
      "明莊里",
      "民權里",
      "海頭里",
      "港仔里",
      "華平里",
      "amy elliot",
      "bradly host",
      "carla ryan",
      "corey petty",
      "david stobbe",
      "jackie chiu",
      "jamie wilde",
      "joe ryan",
      "kyle elliot",
      "laura whitesides host",
      "lesley whitesides",
      "meredith host",
      "patrick mcinerney",
      "taylor host ",
      "taylor host",
      "tom halverson",
      "valerie fay",
      "1983 popayán earthquake",
      "abdomen",
      "adventure",
      "advertising",
      "aegean cat",
      "aerial photography",
      "afterglow",
      "agriculture",
      "air travel",
      "airline",
      "airliner",
      "airplane",
      "airport terminal",
      "album",
      "alcohol",
      "alcoholic beverage",
      "alcoholic drink",
      "ale",
      "alley",
      "almudena cathedral",
      "alpaca",
      "alps",
      "altar",
      "american food",
      "american shorthair",
      "american wirehair",
      "amusement park",
      "amusement ride",
      "ancient history",
      "ancient lives",
      "ancient roman architecture",
      "angkor wat",
      "angle",
      "animal source foods",
      "annual plant",
      "anping old street",
      "antique",
      "apartment",
      "appetizer",
      "arabian coast",
      "arcade",
      "arcangel church san miguel",
      "arch bridge",
      "arch",
      "archaeological site",
      "archaeology",
      "architecture",
      "area",
      "arecales",
      "arena",
      "arm",
      "army",
      "art collection of the bank of the republic",
      "art decoration",
      "art exhibition",
      "art gallery",
      "art museum",
      "art",
      "artful posters",
      "artificial turf",
      "artist",
      "artwork",
      "asian cuisine",
      "asian food",
      "asian soups",
      "asphalt concrete",
      "asphalt",
      "atmosphere of earth",
      "atmosphere",
      "author",
      "automotive design",
      "automotive exterior",
      "autumn",
      "aviation",
      "b.o.g hotel",
      "baan dam black house museum",
      "backpacking",
      "backyard",
      "badlands",
      "bakery",
      "baking stone",
      "balcony",
      "bamboo",
      "banana family",
      "banana",
      "bank of the republic",
      "bank",
      "banner",
      "bannister",
      "baptistery",
      "bar",
      "baseball cap",
      "baseball park",
      "baseball",
      "basilica",
      "batchoy",
      "bath",
      "bathing",
      "batholith",
      "bathtub",
      "batu caves",
      "bay",
      "bayou",
      "bazaar",
      "beach",
      "beak",
      "beauty",
      "bed frame",
      "bed",
      "bedrock",
      "bedroom",
      "beef",
      "beer bottle",
      "beer cocktail",
      "beer glass",
      "beer glassware",
      "beer",
      "behavior",
      "bell tower",
      "bell",
      "berger blanc suisse",
      "bicycle accessory",
      "bicycle saddle",
      "bicycle wheel",
      "bicycle",
      "big rock",
      "bike",
      "biome",
      "bird",
      "bird's eye view",
      "bird's-eye view",
      "birds",
      "black and white",
      "black sand",
      "blog",
      "blue",
      "board games",
      "boardwalk",
      "boat",
      "boating",
      "body of water",
      "bogota",
      "bogotá",
      "bolívar square",
      "bookcase",
      "botanical garden",
      "botero esculturas",
      "bottle",
      "boulder",
      "bowl",
      "box",
      "boy",
      "bracelet",
      "branch",
      "breakfast",
      "breakwater",
      "breed group (dog)",
      "bridge",
      "bridge–tunnel",
      "bridle",
      "british shorthair",
      "bronze sculpture",
      "bronze",
      "brunch",
      "building",
      "buildings",
      "burger",
      "bush",
      "bust",
      "byzantine architecture",
      "bún bò huế",
      "cabin",
      "cabinetry",
      "cable car",
      "cactus",
      "cafe",
      "caffè americano",
      "caldas park",
      "calm",
      "camel like mammal",
      "camera",
      "camping",
      "campus",
      "canal",
      "candle workshop",
      "candles workshop",
      "candles",
      "canh chua",
      "canon powershot sx400 is",
      "canopy",
      "canyon",
      "cao lau",
      "cap",
      "cape",
      "capitolio nacional",
      "car",
      "caribbean sea",
      "carnivoran",
      "cartagena",
      "cartoon",
      "carving",
      "cascading style sheets",
      "casper wells",
      "castle",
      "cat like mammal",
      "cat statue",
      "cat",
      "catamaran",
      "cathedral basilica of our lady of the assumption",
      "cathedral",
      "cattle",
      "cave",
      "caves",
      "ceiling",
      "cemetery",
      "ceramic",
      "chair",
      "chamois",
      "chaparral",
      "chapel",
      "cheek",
      "chelsea f.c.",
      "chest of drawers",
      "chiang mai",
      "chiang rai",
      "chicken",
      "child",
      "children",
      "chin",
      "chinese architecture",
      "chinese cuisine",
      "chinese food",
      "chinese noodles",
      "chopsticks",
      "chow mein",
      "chowder",
      "christmas lights",
      "christmas tree",
      "church tabernacle",
      "church",
      "château",
      "cider",
      "city car",
      "city",
      "cityscape",
      "clam chowder",
      "clam",
      "classical architecture",
      "classical sculpture",
      "cliff",
      "cliffs of moher",
      "clockenflap",
      "clothing",
      "cloud",
      "clouds",
      "cn tower",
      "coast",
      "coastal and oceanic landforms",
      "cocktail",
      "coffee cup",
      "coffee",
      "cola",
      "collection",
      "colombian art",
      "column",
      "comfort food",
      "comfort",
      "commemorative plaque",
      "commercial building",
      "common carp",
      "communal school colombe de la paix",
      "communication",
      "community",
      "compact car",
      "compact mpv",
      "compañía de jesús",
      "computer",
      "concert",
      "concrete",
      "condominium",
      "congress of deputies",
      "contestant",
      "cook",
      "cooked rice",
      "cooking",
      "cookware and bakeware",
      "cool",
      "corn on the cob",
      "corn",
      "corncob",
      "corned beef",
      "costa rica",
      "costume",
      "cottage",
      "couple",
      "courthouse",
      "courtyard",
      "cove",
      "cow goat family",
      "crop",
      "cross",
      "crowd",
      "cruise",
      "cry",
      "crypt",
      "cuglieri",
      "cuisine of the united states",
      "cuisine",
      "culture",
      "cumulus",
      "cup",
      "curry mee",
      "curry",
      "cusco",
      "cutlery",
      "cycle sport",
      "cycling",
      "cyclo-cross bicycle",
      "cyclo-cross",
      "củ chi",
      "daigo-ji",
      "darkness",
      "dawn",
      "day",
      "daylighting",
      "daytime",
      "death",
      "deciduous",
      "deck",
      "deep frying",
      "deity",
      "design",
      "dessert",
      "detroit tigers",
      "detroit",
      "dim sim",
      "dim sum",
      "dinner",
      "dish",
      "display case",
      "display device",
      "distilled beverage",
      "dock",
      "dog breed group",
      "dog breed",
      "dog like mammal",
      "dog",
      "doll",
      "dome",
      "domestic short haired cat",
      "domestic short-haired cat",
      "don't speak",
      "door",
      "downtown",
      "dragon bridge",
      "dragon li",
      "dragon",
      "drawer",
      "drink",
      "drinkware",
      "drunk",
      "dublin",
      "duck boat",
      "duck",
      "ducks geese and swans",
      "durham",
      "dusk",
      "dōtonbori",
      "earth",
      "earthquake",
      "eating",
      "ecoregion",
      "ecosystem",
      "eel rice",
      "egg as food",
      "eggs benedict",
      "electrical supply",
      "electrical",
      "electricity",
      "elevation",
      "emotion",
      "en blanco & negro",
      "english country house",
      "entertainment",
      "equestrianism",
      "eriska",
      "eritrea",
      "eritrean cuisine",
      "escarpment",
      "espresso",
      "estate",
      "ethiopian cuisine",
      "european food",
      "european shorthair",
      "evaporation",
      "evening",
      "event",
      "exhibition",
      "eye",
      "eyebrow",
      "eyelash",
      "eyewear",
      "facade",
      "face",
      "facial expression",
      "facial hair",
      "family car",
      "family",
      "famine",
      "fan",
      "farm",
      "fashion accessory",
      "fashion",
      "fast food restaurant",
      "fast food",
      "fault",
      "fauna",
      "fc barcelona",
      "fell",
      "fence",
      "fernando botero",
      "ferris wheel",
      "ferry",
      "festival",
      "field",
      "figurine",
      "fine art",
      "finger food",
      "finger",
      "fishing vessel",
      "fishing",
      "fixed link",
      "fjord",
      "fk austria wien",
      "flag",
      "flap",
      "flat iron steak",
      "flavor",
      "flesh",
      "flight",
      "floodplain",
      "floor",
      "flooring",
      "flora",
      "floristry",
      "flower",
      "flowering plant",
      "flowers",
      "fluvial landforms of streams",
      "fluvial terrace",
      "fog",
      "font",
      "food",
      "football field",
      "football",
      "footwear",
      "forehead",
      "forest",
      "formation",
      "formosa boulevard station",
      "fort provintia",
      "fort zeelandia",
      "fortification",
      "fountain",
      "fried food",
      "fried wontons",
      "fried",
      "friends",
      "friendship",
      "fruit",
      "full breakfast",
      "fun",
      "fur clothing",
      "fur",
      "furniture",
      "gallery",
      "galliformes",
      "gambling",
      "game show",
      "game",
      "garden",
      "gate",
      "geography",
      "geological phenomenon",
      "geology",
      "girl",
      "glacial landform",
      "glass bottle",
      "glass mask",
      "glass",
      "glasses",
      "glen roy",
      "goat",
      "goats",
      "gold museum",
      "gold",
      "goo",
      "goofy",
      "goose",
      "gothic architecture",
      "graffiti",
      "grandparent",
      "granite",
      "grass family",
      "grass",
      "grasses",
      "grassland",
      "grave",
      "gravy",
      "grazing",
      "great famine",
      "green dot stables",
      "green",
      "greengrocer",
      "grocery store",
      "groundcover",
      "group",
      "guanaco",
      "guanajuato",
      "guard dog",
      "guerrilla warfare",
      "guilty",
      "guitar",
      "gulai",
      "gumbo",
      "ha long bay",
      "hacienda",
      "hae mee",
      "hair",
      "hand",
      "harbor",
      "hardwood",
      "hat",
      "haze",
      "head",
      "headband",
      "headgear",
      "headland",
      "headquarters",
      "headstone",
      "heart for change colombia volunteer program",
      "heart",
      "herd",
      "hi-standard",
      "highland",
      "highway",
      "hiking",
      "hill station",
      "hill",
      "hindu temple",
      "hinduism",
      "hip",
      "historic site",
      "historical",
      "history",
      "ho chi minh",
      "hofburg",
      "hokkien mee",
      "hollywood",
      "home",
      "homeaway",
      "honolulu",
      "horizon",
      "hors d'oeuvre",
      "horse like mammal",
      "horse",
      "hot dog",
      "hot spring",
      "hot springs",
      "hot tub",
      "hotel exe bacata 95",
      "hotel imperial",
      "hotel",
      "house",
      "hub",
      "human behavior",
      "human",
      "hut",
      "hybrid bicycle",
      "ice",
      "igneous rock",
      "illustration",
      "image",
      "inca empire",
      "inca kola",
      "incredible art department",
      "india pale ale",
      "indian cuisine",
      "indian temple",
      "infrastructure",
      "ingredient",
      "inlet",
      "institution",
      "interaction",
      "interior design",
      "internal angle",
      "iron",
      "island hoppin' brewery",
      "island hopping",
      "island",
      "isle of eriska hotel",
      "islet",
      "italian food",
      "italy",
      "jacaranda",
      "jacuzzi",
      "japan women's university",
      "japan",
      "japanese architecture",
      "japanese castle",
      "japanese cuisine",
      "japanese curry",
      "jay",
      "jeans",
      "jersey",
      "jesus",
      "jiaoxi",
      "joint",
      "josai",
      "jungle",
      "junk food",
      "kal-guksu",
      "kalguksu",
      "kaohsiung",
      "karaage",
      "karst landforms",
      "khao soi",
      "kimono",
      "kiss",
      "kitten",
      "klippe",
      "ko lipe",
      "kobe beef",
      "korokke",
      "kuala lumpur",
      "kunsthistorisches museum",
      "kōfuku-ji",
      "laborer",
      "labyrinth",
      "lager",
      "lagoon",
      "lake district",
      "lake",
      "laksa",
      "lamb and mutton",
      "lamian",
      "land lot",
      "land vehicle",
      "landform",
      "landmark",
      "landscape lighting",
      "landscape",
      "landscaping",
      "lane",
      "langkawi",
      "lanterns",
      "laotian cuisine",
      "las vegas strip",
      "las vegas",
      "lawn",
      "le petit futé",
      "leaf vegetable",
      "leaf",
      "leggings",
      "leisure",
      "life jacket",
      "light fixture",
      "light",
      "lighting",
      "lights",
      "lima region",
      "lima travel",
      "lincoln memorial reflecting pool",
      "line",
      "lip",
      "liqueur",
      "listed building",
      "liverpool f.c.",
      "livestock",
      "lizejian bridge",
      "llama",
      "lo's",
      "local food",
      "loch",
      "lomi",
      "lunch",
      "lusitania memorial",
      "luxury vehicle",
      "luxury yacht",
      "macbook pro",
      "macbook",
      "machu picchu",
      "machupicchu district",
      "madrid center- fuencarral pedestrian",
      "madrid",
      "madrid–toledo high-speed rail line",
      "main station of cable car station & funicular",
      "maize",
      "majorelle blue",
      "majorelle garden",
      "malaysian cuisine",
      "maldegem",
      "male",
      "mammal",
      "man with a guitar",
      "man",
      "mane",
      "manor house",
      "mansion",
      "manufactory",
      "mare",
      "marina",
      "market",
      "marketplace",
      "mascot",
      "mask",
      "masque",
      "massage",
      "mast",
      "material",
      "matsusaka beef",
      "maya city",
      "maya civilization",
      "meadow",
      "meal",
      "meat",
      "medellín",
      "medieval architecture",
      "mekong delta",
      "memorial",
      "menchi katsu",
      "menchi-katsu",
      "menu",
      "mergini",
      "metal",
      "meteorological phenomenon",
      "metropolis",
      "metropolitan area",
      "metropolitano el recreo park",
      "mi rebus",
      "michael",
      "microsoft azure",
      "middle ages",
      "milanoguida | visite guidate e mostre a milano",
      "ministry of environment",
      "minivan",
      "miraflores district",
      "mist",
      "misua",
      "mixed use",
      "mixed-use",
      "mode of transport",
      "modern art",
      "molding",
      "money cat",
      "monkey",
      "monster",
      "monument",
      "moray",
      "morning",
      "mosque",
      "mother goddess",
      "mother",
      "motor vehicle",
      "motorbike",
      "motorcycle",
      "mount scenery",
      "mountain bike",
      "mountain goat",
      "mountain pass",
      "mountain range",
      "mountain village",
      "mountain",
      "mountainous landforms",
      "mountains",
      "mouth",
      "mud bath",
      "multi-sport event",
      "mural",
      "muscle",
      "museo botero",
      "museo nacional del prado",
      "museum",
      "music",
      "musical instrument accessory",
      "musical instrument",
      "mustang",
      "nagoya castle honmaru palace",
      "nagoya castle",
      "nam kee",
      "namba",
      "nap",
      "national center for traditional arts",
      "national historic landmark",
      "national park",
      "national trust for places of historic interest or natural beauty",
      "natural foods",
      "natural history museum",
      "natural history",
      "nature reserve",
      "nature",
      "naver blog",
      "naver",
      "neighbourhood",
      "neon",
      "new year's eve",
      "new7wonders of the world",
      "night",
      "ninna-ji",
      "noodle soup",
      "noodle",
      "noodles",
      "nose",
      "ocean",
      "octopus",
      "official residence",
      "oil painting reproduction",
      "oil painting",
      "old-growth forest",
      "on the air",
      "organism",
      "outcrop",
      "outdoor recreation",
      "outdoor structure",
      "outerwear",
      "overhead power line",
      "oyster vermicelli",
      "oysters",
      "pack animal",
      "paddy field",
      "pagoda",
      "paint",
      "painter",
      "painting",
      "palace",
      "palm tree",
      "palm trees",
      "palm",
      "pam trees",
      "pancit",
      "panda",
      "panorama",
      "park",
      "parroquia de san miguel arcángel.",
      "party",
      "passenger",
      "pasture",
      "path",
      "paw",
      "pedestrian",
      "peek",
      "penthouse apartment",
      "people",
      "pepperoni",
      "person",
      "personal flotation device",
      "personal protective equipment",
      "pet",
      "phenomenon",
      "pho",
      "photograph",
      "photography",
      "picture frame",
      "pier",
      "pilgrim",
      "pilgrimage",
      "pillows",
      "pink",
      "pint glass",
      "pint us",
      "pint",
      "pisa",
      "pizza stone",
      "pizza",
      "place of worship",
      "plain",
      "plant community",
      "plant",
      "plantation",
      "plate lunch",
      "plateau",
      "player",
      "plaza de la villa",
      "plaza de oriente",
      "plaza mayor",
      "plaza",
      "polder",
      "pond",
      "pool",
      "poolside restaurant",
      "poolside",
      "porcelain",
      "pork",
      "port",
      "portrait",
      "poster",
      "potato famine",
      "prairie",
      "pray",
      "price is right",
      "primate",
      "primatial cathedral of bogotá",
      "produce",
      "product design",
      "product",
      "professional",
      "promontory",
      "property",
      "public space",
      "public transport",
      "public utility",
      "public",
      "pungsan dog",
      "quarry",
      "rabbit",
      "rabits and hares",
      "race track",
      "race",
      "racing bicycle",
      "rail transport",
      "railing",
      "railroad car",
      "rain",
      "raincoatromantic",
      "rainforest",
      "ramen",
      "ranch",
      "real estate",
      "real madrid c.f.",
      "recipe",
      "recreation",
      "red curry",
      "red meat",
      "red sky at morning",
      "red",
      "reflecting pool",
      "reflection",
      "regensburger hof",
      "relax",
      "religion",
      "religious institute",
      "reservoir",
      "residential area",
      "resort town",
      "resort",
      "resource",
      "restaraunt",
      "restaurant",
      "retail",
      "rib eye steak",
      "rice and curry",
      "rice noodles",
      "rice",
      "ridge",
      "rinkū tokoname station",
      "riparian zone",
      "river terraces",
      "river",
      "rms lusitania",
      "road bicycle",
      "road surface",
      "road trip",
      "road",
      "roast beef",
      "roasting",
      "rock",
      "romantic",
      "roof",
      "rooftop bar",
      "rooftop restaurant",
      "room",
      "rooster",
      "rosewood san miguel",
      "rowing",
      "royal palace of madrid",
      "royal palace of milan",
      "royal sunset drive",
      "royce mansion",
      "rubble",
      "ruins",
      "rural area",
      "saigon beer",
      "saigon river",
      "sail",
      "sailboat",
      "sailing",
      "saimin food",
      "saimin",
      "saint john",
      "salt cathedral of zipaquirá",
      "salt evaporation pond",
      "salt pan",
      "san andrés",
      "san francisco cable car system",
      "san miguel de allende",
      "sanctuary of atotonilco",
      "sanctuary",
      "sand",
      "sandwich",
      "santa maria del carmine",
      "saucer",
      "sculpture",
      "sea of galilee",
      "sea",
      "seabird",
      "seat of local government",
      "sedan",
      "segovia",
      "selfie",
      "senior citizen",
      "serveware",
      "service",
      "shachihoko",
      "shack",
      "shade",
      "shadow",
      "sheep",
      "shelf",
      "shinto shrine",
      "ship",
      "shirt",
      "shoe",
      "shop cat",
      "shopping mall",
      "shopping",
      "shore",
      "short ribs",
      "shoulder",
      "show",
      "shrine",
      "shrub",
      "shrubland",
      "sicilian cuisine",
      "sicilian pizza",
      "side dish",
      "sidewalk",
      "sign",
      "signage",
      "silhouette",
      "sill",
      "sinbad",
      "sindbad's storybook voyage",
      "sinembah tanjung muda hulu",
      "sistine chapel",
      "sitting",
      "skin",
      "skull statue",
      "skull",
      "sky",
      "skyline",
      "skyscraper",
      "sleep",
      "sleeve",
      "slum",
      "small to medium sized cats",
      "smile",
      "snapshot",
      "snout",
      "soccer specific stadium",
      "soccer-specific stadium",
      "socialite",
      "soda",
      "soft drink",
      "soil",
      "soldier",
      "soldiers",
      "son",
      "soup",
      "southeast asia",
      "southeast asian food",
      "spa",
      "space",
      "spandex",
      "spanish language",
      "speleothem",
      "spicy",
      "spire",
      "spoon",
      "sport venue",
      "sport",
      "sporting group",
      "sports equipment",
      "sports",
      "sportswear",
      "spratly islands",
      "spring",
      "st. joseph's cathedral",
      "stadium",
      "stage",
      "stained glass",
      "stainless steel",
      "staircase",
      "stairs",
      "stalactite",
      "stalactites",
      "stalagmite",
      "stallion",
      "stamford bridge",
      "standing",
      "staple food",
      "stately home",
      "stateroom",
      "statue",
      "steamed rice",
      "steaming",
      "steeple",
      "steppe",
      "stew",
      "stock photography",
      "stone carving",
      "stone wall",
      "stone",
      "street 08",
      "street art",
      "street dog",
      "street food",
      "street light",
      "street name sign",
      "street sign",
      "street",
      "structure",
      "stupa",
      "subcompact car",
      "suburb",
      "subway",
      "summer",
      "sun",
      "sunglasses",
      "sunlight",
      "sunrise",
      "sunset",
      "supper",
      "suspension bridge",
      "swamp",
      "swan",
      "sweetness",
      "swimming pool",
      "switches",
      "switzerland",
      "symmetry",
      "synagogue",
      "t shirt",
      "t-shirt",
      "tabby cat",
      "tabernacle chapel",
      "table salt",
      "table",
      "tabletop games",
      "tableware",
      "tail",
      "taipei",
      "taiwan under japanese rule",
      "takahatafudō station",
      "takoyaki",
      "tapestry",
      "tarmac",
      "taste",
      "taxi",
      "tea",
      "team sport",
      "team",
      "teatro juarez",
      "teatro real",
      "technology",
      "temple bar",
      "temple",
      "templo de san francisco",
      "tempura",
      "tenshu",
      "tent",
      "terrace",
      "terrain",
      "text",
      "textile",
      "thai cuisine",
      "thai food",
      "the arts",
      "the bawdies",
      "theater",
      "theatre",
      "theme park",
      "thermae",
      "thigh",
      "thukpa",
      "thumbs up",
      "tianhou temple",
      "tibetan cuisine",
      "tide",
      "tiger beer",
      "tights",
      "time-lapse photography",
      "toddler",
      "tokoname station",
      "tokyo disneysea",
      "toledo",
      "tom kha kai",
      "tonkatsu",
      "tools",
      "tourism",
      "tourist attraction",
      "tournament",
      "tours",
      "tower block",
      "tower",
      "town square",
      "town",
      "toy",
      "trail riding",
      "trail",
      "transmission tower",
      "transport",
      "travel",
      "tray",
      "tree",
      "trees",
      "triumphal arch",
      "trophy",
      "tropical",
      "tropics",
      "trousers",
      "trunk",
      "tuk tuk",
      "tundra",
      "tō-ji",
      "umbrella",
      "unadon",
      "unagi",
      "unesco world heritage site",
      "uniform",
      "united states of america",
      "university of cauca",
      "urban area",
      "vacation",
      "valley",
      "vault",
      "vegetable",
      "vegetarian cuisine",
      "vegetarian food",
      "vegetation",
      "vehicle",
      "vendor",
      "vertebrate",
      "vicuña",
      "vietnam fine arts museum",
      "vietnam people's navy",
      "villa",
      "village",
      "virgin island",
      "vision care",
      "visual arts",
      "volcano",
      "wadi",
      "waikiki",
      "walkway",
      "wall",
      "wallpaper",
      "wat chedi luang",
      "wat rong khun",
      "wat",
      "water bird",
      "water bottle",
      "water feature",
      "water resources",
      "water transportation",
      "water",
      "watercourse",
      "watercraft",
      "waterfall",
      "waterfowl",
      "waterfront",
      "waterway",
      "wave",
      "welcome to fabulous las vegas sign",
      "wetland",
      "wheel",
      "whiskers",
      "white house",
      "white rice",
      "white shepherd",
      "white",
      "whole food",
      "wilderness",
      "wildflower",
      "wildlife",
      "window",
      "wine",
      "wing",
      "winter",
      "woman",
      "women's college",
      "wonders of the world",
      "wood carving",
      "wood stain",
      "wood",
      "woodland",
      "woody plant",
      "workshop",
      "world heritage site",
      "worship",
      "wufeng road",
      "xiaolongbao",
      "yacht",
      "yakiniku",
      "yakisoba",
      "yard",
      "yellow",
      "yokohama landmark tower",
      "zipaquirá",
      "zoo",
      "đồ sơn"]
  },
  getters: {
    getKeywords: state => state.keywords,
    getKeywordsTracker: state => state.hardCoded,
    getThumbnailSrc: state => state.thumbnailSrc,
    getThumbnailActive: state => state.thumbnailActive,
  },
  mutations: {
    sortKeywords:(state, payload) => {
      //sort keywords into an array to display on autocomplete
      const keywords = [];
      // const keywordsTracker = [];
      // const keywordArrays = payload.map((item, index) => {
      //   item._source.keywords.forEach((keyword)=> {
      //     if(!keywordsTracker.includes(keyword)) {
      //       keywords.push({name:keyword})
      //       keywordsTracker.push(keyword);
      //     }
      //   })
      // });

      state.hardCoded.forEach((item) => {
        keywords.push({name:item})
      })

      state.keywords = keywords;
      state.keywordsTracker = keywordsTracker;
    },
    setThumbnailSrc:(state, payload) => {
      state.thumbnailSrc = payload
      state.thumbnailActive = true;
    },
    setThumbnailUnActive:(state) => {
      state.thumbnailActive = false;
    }
  },
  actions: {
    retrieveKeywords:(context) => {
      // on load get search terms to auto complete with.
      context.commit('sortKeywords', context.rootState.elasticSearch.responseData);
    },
    retrieveThumbnail:(context, payload) => {
      context.commit('setThumbnailSrc', payload)
    },
    turnOffThumbnail: (context) => {
      context.commit('setThumbnailUnActive')
    }
  }
}

export default searchTerms
